"""Initial migration: users, servers, backups

Revision ID: 82cfdd2cd04f
Revises:
Create Date: 2025-11-03 01:40:30.932936

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "82cfdd2cd04f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "servers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "server_type",
            sa.Enum(
                "VANILLA",
                "PAPER",
                "SPIGOT",
                "FABRIC",
                "FORGE",
                "NEOFORGE",
                "PURPUR",
                name="servertype",
            ),
            nullable=False,
        ),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("rcon_port", sa.Integer(), nullable=False),
        sa.Column("rcon_password", sa.String(length=255), nullable=False),
        sa.Column("memory_mb", sa.Integer(), nullable=False),
        sa.Column("container_id", sa.String(length=255), nullable=True),
        sa.Column("container_name", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "STOPPED",
                "STARTING",
                "RUNNING",
                "STOPPING",
                "ERROR",
                name="serverstatus",
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_started_at", sa.DateTime(), nullable=True),
        sa.Column("last_stopped_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("container_name"),
        sa.UniqueConstraint("port"),
        sa.UniqueConstraint("rcon_port"),
    )
    op.create_index(op.f("ix_servers_id"), "servers", ["id"], unique=False)
    op.create_index(op.f("ix_servers_name"), "servers", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "MODERATOR", "VIEWER", name="userrole"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "backups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("is_automatic", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["server_id"], ["servers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_backups_id"), "backups", ["id"], unique=False)
    op.create_index(
        op.f("ix_backups_server_id"), "backups", ["server_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_backups_server_id"), table_name="backups")
    op.drop_index(op.f("ix_backups_id"), table_name="backups")
    op.drop_table("backups")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_servers_name"), table_name="servers")
    op.drop_index(op.f("ix_servers_id"), table_name="servers")
    op.drop_table("servers")
    # ### end Alembic commands ###
