"""add current_session_logs to servers

Revision ID: aee4349c6e61
Revises: 01efedaf6a66
Create Date: 2025-11-04 07:08:26.043403

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "aee4349c6e61"
down_revision: Union[str, Sequence[str], None] = "01efedaf6a66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "backups",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "refresh_tokens",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.add_column(
        "servers", sa.Column("current_session_logs", mysql.MEDIUMTEXT(), nullable=True)
    )
    op.alter_column(
        "servers",
        "has_been_started",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "servers",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "servers",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "system_settings",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "system_settings",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_server_permissions",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_server_permissions",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_server_permissions",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_server_permissions",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    op.alter_column(
        "system_settings",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    op.alter_column(
        "system_settings",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    op.alter_column(
        "servers",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    op.alter_column(
        "servers",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    op.alter_column(
        "servers",
        "has_been_started",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("'0'"),
        existing_nullable=False,
    )
    op.drop_column("servers", "current_session_logs")
    op.alter_column(
        "refresh_tokens",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    op.alter_column(
        "backups",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
